### ISSUE TITLE
Existe uma forma de coletar o nome da pessoa que esta mandando a msg?

### ISSUE THREAD

**Issue by Rafamt16** [pedroentringer/bot-whatsapp-services#8]
Podemos coletar o número da pessoa utilizando o FROM.
Teria alguma forma de coletar o nome da pessoa que mandou a msg, aquele nome que a pessoa coloca no  Whatsapp?

**Comment by pedroentringer** [comment]
> Podemos coletar o número da pessoa utilizando o FROM. Teria alguma forma de coletar o nome da pessoa que mandou a msg, aquele nome que a pessoa coloca no Whatsapp?

Sim, é possível.
Você irá receber a mensagem e usar essa função https://docs.wwebjs.dev/Message.html#getContact que vai te retornar o contado do usuário, seguindo este modelo: https://docs.wwebjs.dev/Contact.html

Compartilha conosco se conseguiu realizar :D
Abraax

**Comment by Rafamt16** [comment]
Olá,
Funcionou perfeitamente!
Muito obrigado pela dica, ficou muito bom.
Seu projeto é top

Abarço

**Comment by pedroentringer** [comment]
Show de bola @Rafamt16, fico feliz que deu certo!
Conte comigo e muito obrigado!!
Abraax.
